# Generated by Django 4.2.3 on 2024-10-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='user',
        ),
        migrations.AddField(
            model_name='patient',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
