# Generated by Django 4.2.3 on 2024-10-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_remove_patient_user_patient_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='user',
        ),
        migrations.AddField(
            model_name='doctor',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
