# Generated by Django 4.2.3 on 2024-10-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0003_remove_doctor_user_doctor_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_image',
            field=models.ImageField(default='default_profile.png', upload_to='profile_images/'),
        ),
    ]
