# Generated by Django 4.2.3 on 2024-10-10 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0010_county'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('side_effects', models.TextField()),
                ('availability', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospitals', to='hospital.region')),
            ],
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('preventive_measures', models.TextField()),
                ('treatment_info', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='disease_images/')),
                ('affected_regions', models.ManyToManyField(related_name='diseases', to='hospital.region')),
                ('medications', models.ManyToManyField(related_name='diseases', to='hospital.medication')),
            ],
        ),
    ]
